/* WRITES ../database.rules.next.json FROM NAMED PIECES.
 *
 * The rules are long strings that differ by one word, repeated a dozen times — exactly the shape a
 * slip hides in. The first hand-written draft left the owner out of every one of them. Here each idea
 * is said once (who an admin is, what holding a right means) and the file is assembled from those.
 *
 *   node build-rules.js        → writes the draft; deploy it with rules-tool.js, never by hand
 */
const fs = require('fs'), pathm = require('path');

const OWNER = 'ravi@thefabricrush.com';
const VKEY = "auth.token.email.replace('.', ',')";                       // as pt_vendorByEmail has always been keyed
const KEY = "auth.token.email.toLowerCase().replace('.', ',')";
const ME = `root.child('pt_perms').child(${KEY})`;
const NOT_VENDOR = `!root.child('pt_vendorByEmail').child(${VKEY}).exists()`;

const STAFF = `auth != null && ${NOT_VENDOR}`;
const ADMIN = `(auth.token.email.toLowerCase() === '${OWNER}' || ${ME}.child('admin').val() === true)`;
const right = r => `${ME}.child('r').child('${r}').val() === true`;
const tab = t => `${ME}.child('t').child('${t}').val() === true`;
const any = (...xs) => `auth != null && (${xs.join(' || ')})`;
const OWN_BRANCH = `auth != null && root.child('pt_vendorByEmail').child(${VKEY}).child('code').val() === $code`;
const OWN_ROW = `auth != null && $emailKey === ${VKEY}`;
const PENDING = "(!data.exists() || data.child('status').val() === 'Pending') && (!newData.exists() || newData.child('status').val() === 'Pending')";

const staffIndexed = ix => ({ '.write': STAFF, '.indexOn': ix });

const rules = {
  '.read': STAFF,

  pt_perms: { '.write': any(ADMIN) },
  pt_payoutFreezes: { '.write': any(ADMIN) },

  /* PHASE 2 — a rate is a row, and the row's own words decide who may write it. */
  pt_printerRates: {
    '.write': any(ADMIN, right('rateApprove')),
    $id: { '.write': `auth != null && ${tab('hr')} && ${PENDING}` },
  },
  pt_rateList: { '.write': any(ADMIN, tab('hr')) },
  pt_advances: { '.write': any(ADMIN, tab('hr')) },
  pt_empList: { '.write': any(ADMIN, tab('hr'), right('empEdit')) },

  pt_masterDB: { '.write': any(ADMIN, right('mdbEdit'), right('prodEdit')), '.indexOn': ['sku', 'brand', 'articleType', 'color'] },

  /* PHASE 2 — the master lists, each by the right the app already asks for before writing it. */
  pt_masters: {
    accessories: { '.write': any(ADMIN, right('accEdit')) },
    ruffleRule: { '.write': any(ADMIN, right('prodEdit')) },
    printRule: { '.write': any(ADMIN, right('prodEdit')) },
    recipe: { '.write': any(ADMIN, right('mdbEdit')) },
    $list: { '.write': any(ADMIN) },
  },

  /* PHASE 2 — who is a vendor, and which vendor. Deleting a row here used to promote a vendor to staff. */
  pt_vendorByEmail: { '.write': any(ADMIN), $emailKey: { '.read': OWN_ROW } },
  pt_loginDir: { '.write': any(ADMIN) },
  pt_vendorMap: { '.write': any(ADMIN, right('vreqApprove')) },
  pt_vendorPin: {
    '.write': any(ADMIN),
    $emailKey: { '.read': OWN_ROW, '.write': `${OWN_ROW} && newData.hasChildren(['changedAt'])` },
  },

  pt_vendorOrders: { '.write': STAFF, $code: { '.read': OWN_BRANCH, '.write': OWN_BRANCH } },

  pt_baseData: staffIndexed(['sku', 'empName', 'issueDate', 'frozen']),
  pt_cuttingData: staffIndexed(['sku', 'orderNo', 'cutDate']),
  pt_pressInventory: staffIndexed(['sku', 'orderNo', 'entryDate']),
  pt_orderBook: staffIndexed(['sku', 'orderNo', 'orderDate']),
  pt_customSkus: staffIndexed(['sku', 'brand', 'articleType']),
  pt_fabInvLedger: staffIndexed(['orderNo', 'date', 'fabricType']),
  pt_qcChecks: staffIndexed(['sku', 'date']),
  pt_qcIssuance: staffIndexed(['sku', 'date', 'employee']),
  pt_extraHours: staffIndexed(['date', 'empName', 'status']),
  pt_salesOrders: staffIndexed(['orderNo', 'orderDate', 'channel']),

  $other: { '.write': STAFF },
};

const HEAD = `{
  // ── THE DATABASE ENFORCES WHO MAY WRITE WHAT ─────────────────────────────────────────────────────
  //
  // GENERATED by rules/build-rules.js — change that, not this. Deploy with rules/rules-tool.js, which
  // plays every account against the new rules and puts the old ones back by itself if one answer is
  // not the expected one.
  //
  // Until 2026-09-19 every right in the app — approve a rate, freeze a payout, edit the master
  // database — was a button the app chose to show or hide; the database let any signed-in member of
  // staff write anything. 177 (account, node) pairs could write what they should not.
  //
  // THE ROOT GRANTS READ ONLY. A grant given at a parent cannot be taken back lower down, so while the
  // root said "any staff may write" no stricter rule beneath it could mean anything. Write is granted
  // node by node, and EVERYTHING NOT NAMED stays staff-writable through "$other" — a node nobody
  // thought of is what it was yesterday, not locked.
  //
  // A NODE NAMED HERE IS NOT COVERED BY "$other" — the indexed nodes each repeat the staff grant.
  //
  // THE APP PATCHES AT THE ROOT with keys like "pt_masters/recipe/x"; that is judged key by key
  // (proven on the live database with a simulated vendor before the root grant was removed).
  //
  // THE OWNER IS ALWAYS AN ADMIN, by email, as firestore.rules (OWNER_EMAIL) and the app both have it.
  //
  // THE RIGHTS live in Firestore, which these rules cannot read. pt_perms/<email, dots as commas> is
  // the copy they can: { admin, r: {right: true}, t: {tab: true} }. Sellora's Access screen writes
  // both; only an admin may write pt_perms; rules-tool.js "drift" says when the two differ.
  //
  // A RATE IS A ROW (phase 2). Whoever holds Finance & HR may write a row that is, and stays, Pending.
  // Only an approver may write one that is Approved — and a row with no status at all IS approved,
  // which is why the test is "=== 'Pending'" and never "!== 'Approved'".
  "rules": `;

const body = JSON.stringify(rules, null, 2).split('\n').map((l, i) => (i ? '  ' + l : l)).join('\n');
const out = pathm.join(__dirname, '..', 'database.rules.next.json');
fs.writeFileSync(out, HEAD + body + '\n}\n');
console.log('written', out, '—', Object.keys(rules).filter(k => k[0] !== '.').length, 'nodes named');
